name: Make Distribution

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  make_dist:
    name: Make Distribution File(macos)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          cache: "pip"
          cache-dependency-path: |
            requirements.txt
      
      - name: Install dependencies
        run: |
          python -m pip install -U -r requirements.txt

      - name: Make dist(MacOS)
        run: |
          pyinstaller --noconsole --onefile --windowed --icon=logo.ico app.py

      - name: Remove Useless file
        run: rm -rf dist/WordsOut

      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: WordsOut-${{github.ref_name}}-macos.zip
          directory: dist
      
      - name: macOS Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          files: dist/WordsOut-${{github.ref_name}}-macos.zip